---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: k8s/overlays/25gxs-dev
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: fundamentus
  name: fundamentus-subscription
  namespace: fundamentus
spec:
  channel: fundamentus-channel-ns/fundamentus-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: fundamentus-placement
