kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-fundamentus
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:fundamentus-prod:prod-fundamentus-sa
